imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }


# app/config/config.yml
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: UserBundle\Entity\User
    registration:
            form:
                type: app_user_registration

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    translator:      { fallback: "%locale%" }
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        gc_probability: 0
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        contact_email:    "%contact_email%"

# Assetic Configuration
assetic:
    bundles: [ AppBundle, FOSUserBundle ]
    assets:
        bootstrap_css:
          inputs:
            - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/css/bootstrap.css
          filters:
            - cssrewrite
          output: css/bootstrap.css

        bootstrap_js:
            inputs:
                - %kernel.root_dir%/../vendor/twitter/bootstrap/js/affix.js
                - %kernel.root_dir%/../vendor/twitter/bootstrap/js/alert.js
                - %kernel.root_dir%/../vendor/twitter/bootstrap/js/button.js
                - %kernel.root_dir%/../vendor/twitter/bootstrap/js/carousel.js
                - %kernel.root_dir%/../vendor/twitter/bootstrap/js/collapse.js
                - %kernel.root_dir%/../vendor/twitter/bootstrap/js/dropdown.js
                - %kernel.root_dir%/../vendor/twitter/bootstrap/js/modal.js
                - %kernel.root_dir%/../vendor/twitter/bootstrap/js/tooltip.js
                - %kernel.root_dir%/../vendor/twitter/bootstrap/js/popover.js
                - %kernel.root_dir%/../vendor/twitter/bootstrap/js/scrollspy.js
                - %kernel.root_dir%/../vendor/twitter/bootstrap/js/tab.js
                - %kernel.root_dir%/../vendor/twitter/bootstrap/js/transition.js
            output: js/bootstrap.js

        fontawesome_css:
          inputs:
            - %kernel.root_dir%/../vendor/fontawesome/fontawesome/css/font-awesome.css
          output: css/fontawesome.css
        font-awesome-otf:
          inputs:
            - %kernel.root_dir%/../vendor/fontawesome/fontawesome/fonts/FontAwesome.otf
          output: fonts/FontAwesome.otf
        font-awesome-eot:
          inputs:
            - %kernel.root_dir%/../vendor/fontawesome/fontawesome/fonts/fontawesome-webfont.eot
          output: fonts/fontawesome-webfont.eot
        font-awesome-svg:
          inputs:
            - %kernel.root_dir%/../vendor/fontawesome/fontawesome/fonts/fontawesome-webfont.svg
          output: fonts/fontawesome-webfont.svg
        font-awesome-ttf:
          inputs:
            - %kernel.root_dir%/../vendor/fontawesome/fontawesome/fonts/fontawesome-webfont.ttf
          output: fonts/fontawesome-webfont.ttf
        font-awesome-woff:
          inputs:
            - %kernel.root_dir%/../vendor/fontawesome/fontawesome/fonts/fontawesome-webfont.woff
          output: fonts/fontawesome-webfont.woff

        jquery:
          inputs:
            - %kernel.root_dir%/../vendor/components/jquery/jquery.js
          output: js/jquery.js

        main:
          inputs:
            - %kernel.root_dir%/../app/Resources/css/main.css
          filters:
            - cssrewrite
          output: css/main.css

        layout:
          inputs:
            - %kernel.root_dir%/../app/Resources/css/layout.css
          filters:
            - cssrewrite
          output: css/layout.css

        twit:
          inputs:
            - %kernel.root_dir%/../src/AppBundle/Resources/public/css/twit.css
          filters:
            - cssrewrite
          output: css/twit.css

        login:
          inputs:
            - %kernel.root_dir%/../src/AppBundle/Resources/public/css/login.css
          output: css/login.css

        landingpage:
          inputs:
            - %kernel.root_dir%/../src/AppBundle/Resources/public/css/landingpage.css
          output: css/landingpage.css

    debug:          "%kernel.debug%"
    use_controller: false
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        lessphp:
            file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
            apply_to: ".less$"

        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
