# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_USER:       ROLE_USER
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        in_memory:
            memory:
                users:
                    admin:
                        password: adminpass
                        roles: 'ROLE_ADMIN'

    firewalls:
        admin:
            pattern:    ^/admin/.*
            http_basic:
                provider: in_memory

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path:          fos_user_security_login
                check_path:          fos_user_security_check



            logout:
              path:   fos_user_security_logout
            anonymous:    true




    access_control:
        - { path: ^/[^/]+/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[^/]+/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[^/]+/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[^/]+/admin/, role: ROLE_ADMIN }
        - { path: ^/[^/]+/settings/, role: ROLE_ADMIN }
        - { path: ^/[^/]+/twit/, role: ROLE_USER }
        - { path: ^/[^/]+/user/, role: ROLE_USER }
        - { path: ^/[^/]+/, role: IS_AUTHENTICATED_ANONYMOUSLY }
