# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

      app.twits:
        class: AppBundle\Model\TwitManager
        arguments: ['@doctrine.orm.default_entity_manager', '@security.context']


      monolog.formatter.log_listener:
              class: Monolog\Formatter\LineFormatter
              arguments:
                  - "[%%datetime%%] %%channel%%.%%level_name%%: %%message%%\n"


      app.log_listener:
              class: AppBundle\EventListener\LogListener
              arguments: ['@logger']
              tags:
                  - { name: monolog.logger, channel: request_info }
                  - { name: kernel.event_listener, event: kernel.request}

      app.form.registration:
              class: AppBundle\Form\RegistrationType
              tags:
                  - { name: form.type, alias: app_user_registration }

